# Retail Sales Analytics using Python, SQL & Tableau

## Project Overview

This project analyzes retail sales data to uncover insights into customer behavior, sales trends, product performance, and regional performance.

The project follows the complete data analytics workflow:

- Data Understanding
- Data Cleaning
- Feature Engineering
- Exploratory Data Analysis (EDA)
- SQL Analysis
- Interactive Tableau Dashboard

### Tools Used

- Python (Pandas, NumPy)
- Matplotlib
- Seaborn
- SQL (MySQL)
- Tableau

# 1. Import Libraries

In [54]:
import pandas as pd
import numpy as np


# Display all columns
pd.set_option("display.max_columns", None)

# Better plot appearance
plt.style.use("ggplot")

print("Libraries imported successfully!")

Libraries imported successfully!

# 2. Load Dataset

In [2]:
# Load the retail sales dataset
df = pd.read_csv("../data/raw/superstore_final_dataset.csv")

# Display first five rows
df.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O Donnel,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O Donnel,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold N Roll Cart System,22.3680

# 3. Data Understanding

In [3]:
# Number of rows and columns

print(f"Number of Rows    : {df.shape[0]}")
print(f"Number of Columns : {df.shape[1]}")

Number of Rows    : 9800
Number of Columns : 18

In [ ]:
# Display information about dataset

df.info()
# Display data types

df.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row_ID         9800 non-null   int64
 1   Order_ID       9800 non-null   object
 2   Order_Date     9800 non-null   object
 3   Ship_Date      9800 non-null   object
 4   Ship_Mode      9800 non-null   object
 5   Customer_ID    9800 non-null   object
 6   Customer_Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal_Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product_ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub_Category   9800 non-null   object
 16  Product_Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [4]:
# Summary statistics

df.describe()

            Row_ID   Postal_Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

### Date column has been correctly parsed and formatted.

In [ ]:
# Display column names

df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row_ID         9800 non-null   int64
 1   Order_ID       9800 non-null   object
 2   Order_Date     9800 non-null   datetime64[ns]
 3   Ship_Date      9800 non-null   datetime64[ns]
 4   Ship_Mode      9800 non-null   object
 5   Customer_ID    9800 non-null   object
 6   Customer_Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal_Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product_ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub_Category   9800 non-null   object
 16  Product_Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: datetime64[ns](2), float64(2), int64(1), object(13)
memory usage: 1.3+ MB

In [5]:
# Check missing values

df.isnull().sum()

Row_ID            0
Order_ID          0
Order_Date        0
Ship_Date         0
Ship_Mode         0
Customer_ID       0
Customer_Name     0
Segment           0
Country           0
City              0
State             0
Postal_Code      11
Region            0
Product_ID        0
Category          0
Sub_Category      0
Product_Name      0
Sales             0
dtype: int64

### Only the Postal_Code has null values. Let's drop these rows as they are less in numbers.

In [6]:
# Check duplicate rows

print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [7]:
# Display random records

df.sample(5)

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales
3522,3523,CA-2017-114482,21/11/2017,25/11/2017,Second Class,DM-13345,Denise Monton,Corporate,United States,Des Moines,Iowa,50315.0,Central,TEC-PH-10001580,Technology,Phones,Logitech Mobile Speakerphone P710e - speaker p...,404.940
1685,1686,CA-2018-149489,24/04/2018,27/04/2018,First Class,DK-12835,Damala Kotsonis,Corporate,United States,Philadelphia,Pennsylvania,19143.0,East,OFF-BI-10002813,Office Supplies,Binders,Avery Reinforcements for Hole-Punch Pages,1.188
4681,4682,CA-2017-169215,14/07/2017,18/07/2017,Second Class,RE-19450,Richard Eichhorn,Consumer,United States,Auburn,New York,13021.0,East,OFF-FA-10000936,Office Supplies,Fasteners,Acco Hot Clips Clips to Go,29.610
7861,7862,CA-2016-142993,12/10/2016,17/10/2016,Standard Class,KA-16525,Kelly Andreada,Consumer,United States,Seattle,Washington,98103.0,West,TEC-AC-10003038,Technology,Accessories,Kingston Digital DataTraveler 16GB USB 2.0,17.900
6746,6747,CA-2018-159156,13/11/2018,16/11/2018,First Class,KB-16600,Ken Brennan,Corporate,United States,New York City,New York,10009.0,East,TEC-PH-10004389,Technology,Phones,Nokia Lumia 925,629.950

In [8]:
# Number of unique values in each column

df.nunique()

Row_ID           9800
Order_ID         4922
Order_Date       1230
Ship_Date        1326
Ship_Mode           4
Customer_ID       793
Customer_Name     793
Segment             3
Country             1
City              529
State              49
Postal_Code       626
Region              4
Product_ID       1861
Category            3
Sub_Category       17
Product_Name     1849
Sales            5757
dtype: int64

### Initial Findings

- The dataset contains retail sales transactions.
- There are 18 columns describing orders, customers, products, and locations.
- Missing values are present only in the Postal_Code column.
- Duplicate records will be examined before cleaning.
- Date columns will be converted into datetime format during preprocessing.

# 4. Data Cleaning

Data cleaning prepares the dataset for analysis by handling missing values, correcting data types, removing duplicates, and validating data quality.

In [10]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"], dayfirst=True)
df["Ship_Date"] = pd.to_datetime(df["Ship_Date"], dayfirst=True)

## Handling Missing Values

Before performing analysis, we inspect the dataset for missing values. Since only the `Postal_Code` column contains a small number of missing values and it is not critical for our planned analysis, these records will be removed.

In [11]:
# Check missing values

df.isnull().sum()

Row_ID            0
Order_ID          0
Order_Date        0
Ship_Date         0
Ship_Mode         0
Customer_ID       0
Customer_Name     0
Segment           0
Country           0
City              0
State             0
Postal_Code      11
Region            0
Product_ID        0
Category          0
Sub_Category      0
Product_Name      0
Sales             0
dtype: int64

In [12]:
# Remove rows with missing postal codes

df = df.dropna(subset=["Postal_Code"])

In [13]:
# Verify missing values have been removed

df.isnull().sum()

Row_ID           0
Order_ID         0
Order_Date       0
Ship_Date        0
Ship_Mode        0
Customer_ID      0
Customer_Name    0
Segment          0
Country          0
City             0
State            0
Postal_Code      0
Region           0
Product_ID       0
Category         0
Sub_Category     0
Product_Name     0
Sales            0
dtype: int64

In [14]:
# Convert Postal_Code to integer

df["Postal_Code"] = df["Postal_Code"].astype(int)

In [15]:
df.dtypes

Row_ID                    int64
Order_ID                    str
Order_Date       datetime64[us]
Ship_Date        datetime64[us]
Ship_Mode                   str
Customer_ID                 str
Customer_Name               str
Segment                     str
Country                     str
City                        str
State                       str
Postal_Code               int64
Region                      str
Product_ID                  str
Category                    str
Sub_Category                str
Product_Name                str
Sales                   float64
dtype: object

## Duplicate Records

Duplicate records can lead to incorrect analysis by counting the same transaction multiple times. We check for duplicates and remove them if necessary.

In [16]:
# Check duplicate records

print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [17]:
# Remove duplicate rows

df = df.drop_duplicates()

In [18]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

## Data Validation

To ensure data quality, we verify that every order was shipped on or after the order date.

In [19]:
# Check for invalid shipping dates

invalid_dates = df[df["Ship_Date"] < df["Order_Date"]]

print("Invalid Records:", len(invalid_dates))

Invalid Records: 0

In [20]:
# Final shape after cleaning

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 9789
Columns: 18

In [21]:
# Save cleaned dataset

df.to_csv("../data/cleaned/superstore_sales_cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

# 5. Feature Engineering

Feature engineering involves creating new variables from existing data to improve analysis and generate meaningful business insights. These new features will help identify sales trends, seasonal patterns, and shipping performance.

In [22]:
# Extract year from Order_Date

df["Order_Year"] = df["Order_Date"].dt.year

In [23]:
df[["Order_Date", "Order_Year"]].head()

  Order_Date  Order_Year
0 2017-11-08        2017
1 2017-11-08        2017
2 2017-06-12        2017
3 2016-10-11        2016
4 2016-10-11        2016

In [24]:
# Extract month number

df["Order_Month"] = df["Order_Date"].dt.month

In [25]:
df[["Order_Date","Order_Month"]].head()

  Order_Date  Order_Month
0 2017-11-08           11
1 2017-11-08           11
2 2017-06-12            6
3 2016-10-11           10
4 2016-10-11           10

In [26]:
# Extract month name

df["Month_Name"] = df["Order_Date"].dt.month_name()

In [27]:
df[["Order_Date","Month_Name"]].head()

  Order_Date Month_Name
0 2017-11-08   November
1 2017-11-08   November
2 2017-06-12       June
3 2016-10-11    October
4 2016-10-11    October

In [28]:
# Extract quarter

df["Quarter"] = df["Order_Date"].dt.quarter

In [29]:
df[["Order_Date","Quarter"]].head()

  Order_Date  Quarter
0 2017-11-08        4
1 2017-11-08        4
2 2017-06-12        2
3 2016-10-11        4
4 2016-10-11        4

In [30]:
# Calculate shipping time in days

df["Shipping_Days"] = (df["Ship_Date"] - df["Order_Date"]).dt.days

In [31]:
df[["Order_Date","Ship_Date","Shipping_Days"]].head()

  Order_Date  Ship_Date  Shipping_Days
0 2017-11-08 2017-11-11              3
1 2017-11-08 2017-11-11              3
2 2017-06-12 2017-06-16              4
3 2016-10-11 2016-10-18              7
4 2016-10-11 2016-10-18              7

In [32]:
df.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,State,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales,Order_Year,Order_Month,Month_Name,Quarter,Shipping_Days
0,1,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2017,11,November,4,3
1,2,CA-2017-152156,2017-11-08,2017-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,2017,11,November,4,3
2,3,CA-2017-138688,2017-06-12,2017-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2017,6,June,2,4
3,4,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O Donnel,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,2016,10,October,4,7
4,5,US-2016-108966,2016-10-11,2016-10-18,Standard Class,SO-20335,Sean O Donnel,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold N Roll Cart System,22.3680,2016,10,October,4,7

In [33]:
df.to_csv("../data/cleaned/superstore_sales_cleaned.csv", index=False)

print("Feature engineered dataset saved successfully!")

Feature engineered dataset saved successfully!

# 6. Exploratory Data Analysis (EDA)

The objective of this section is to explore the cleaned dataset, identify trends, and answer important business questions using descriptive statistics and visualizations.

## Business Question 1

### Which region generates the highest sales revenue?

In [34]:
# Sales by Region

region_sales = df.groupby("Region")["Sales"].sum().sort_values(ascending=False)

region_sales

Region
West       710219.6845
East       660589.3560
Central    492646.9132
South      389151.4590
Name: Sales, dtype: float64

### Business Insight

The West region generated the highest sales, indicating strong customer demand and market performance. Regions with comparatively lower sales may require additional marketing efforts or operational improvements.

In [36]:
category_sales = df.groupby("Category")["Sales"].sum().sort_values(ascending=False)

category_sales

Category
Technology         825856.1130
Furniture          723538.4757
Office Supplies    703212.8240
Name: Sales, dtype: float64

### Business Insight

Technology products contribute the highest sales, followed by Furniture and Office Supplies. The company should continue investing in high-performing categories while identifying opportunities to improve lower-performing categories.

In [38]:
segment_sales = df.groupby("Segment")["Sales"].sum().sort_values(ascending=False)

segment_sales

Segment
Consumer       1.146708e+06
Corporate      6.822118e+05
Home Office    4.236874e+05
Name: Sales, dtype: float64

### Business Insight

The Consumer segment contributes the largest share of sales, making it the company's primary customer base.

In [40]:
monthly_sales = df.groupby("Month_Name")["Sales"].sum()

monthly_sales

Month_Name
April        134988.2506
August       157315.9270
December     321275.1395
February      59371.1154
January       91982.1396
July         145535.6890
June         145837.5233
March        197573.5872
May          154086.7237
November     345041.6110
October      199496.2947
September    300103.4117
Name: Sales, dtype: float64

In [41]:
# Monthly sales trend

month_order = [
    "January","February","March","April","May","June",
    "July","August","September","October","November","December"
]

monthly_sales = (
    df.groupby("Month_Name")["Sales"]
      .sum()
      .reindex(month_order)
)

monthly_sales

Month_Name
January       91982.1396
February      59371.1154
March        197573.5872
April        134988.2506
May          154086.7237
June         145837.5233
July         145535.6890
August       157315.9270
September    300103.4117
October      199496.2947
November     345041.6110
December     321275.1395
Name: Sales, dtype: float64

In [43]:
top_customers = (
    df.groupby("Customer_Name")["Sales"]
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

top_customers

Customer_Name
Sean Miller           25043.050
Tamara Chand          19052.218
Raymond Buch          15117.339
Tom Ashbrook          14595.620
Adrian Barton         14473.571
Ken Lonsdale          14175.229
Sanjit Chand          14142.334
Hunter Lopez          12873.298
Sanjit Engle          12209.438
Christopher Conant    12129.072
Name: Sales, dtype: float64

A relatively small number of customers contribute significantly to total sales. Retaining these high-value customers can have a meaningful impact on revenue.

In [45]:
top_cities = (
    df.groupby("City")["Sales"]
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

top_cities

City
New York City    252462.5470
Los Angeles      173420.1810
Seattle          116106.3220
San Francisco    109041.1200
Philadelphia     108841.7490
Houston           63956.1428
Chicago           47820.1330
San Diego         47521.0290
Jacksonville      44713.1830
Detroit           42446.9440
Name: Sales, dtype: float64

In [47]:
shipping = df["Ship_Mode"].value_counts()

shipping

Ship_Mode
Standard Class    5849
Second Class      1901
First Class       1501
Same Day           538
Name: count, dtype: int64

In [51]:
top_products = (
    df.groupby("Product_Name")["Sales"]
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

top_products

Product_Name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
GBC Ibimaster 500 Manual ProClick Binding System                               19024.500
Hewlett Packard LaserJet 3310 Copier                                           18839.686
HP Designjet T520 Inkjet Large Format Printer - 24 Color                       18374.895
GBC DocuBind P400 Electric Binding System                                      17965.068
High Speed Automatic Electric Letter Opener                                    17030.312
Name: Sales, dtype: float64

# Conclusion

The analysis explored sales performance across different regions, product categories, customer segments, cities, and time periods. Feature engineering enabled additional business insights such as monthly trends and shipping performance. The cleaned dataset is now ready for SQL analysis and Tableau dashboard development.